=== MomoAy/XML/encyclopedie.xsd
<?xml version="1.0" encoding="UTF-8"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="encyclopedie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personne" type="person" maxOccurs="4"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="person">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="publication" type="xs:string" maxOccurs="2"/>
        </xs:sequence>
        <xs:attribute name="datenaissance" type="xs:date"/>
        <xs:attribute name="sexe" type="xs:string"/>    
    </xs:complexType>
</xs:schema>

=== MomoAy/XML/encyclopedie.xml
<?xml version="1.0" encoding="UTF-8"?>
<encyclopedie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="encyclopedie.xsd"> 
    <personne datenaissance="1942-01-08" sexe="H"> 
        <nom>HAWKING</nom> 
        <prenom>Stephen</prenom> 
        <publication>Une brève histoire du temps</publication> 
    </personne> 
    <personne datenaissance="1932-07-13" sexe="H"> 
        <nom>REEVES</nom> 
        <prenom>Hubert</prenom> 
        <publication>L'Univers expliqué à mes petitsenfants</publication> 
    </personne> 
    <personne datenaissance="1879-03-14" sexe="H"> 
        <nom>EINSTEN</nom> 
        <prenom>Albert</prenom> 
        <publication>Des ondes gravitationnelles </publication> 
        <publication>Sur la théorie quantique du rayonnement </publication> 
    </personne> 
    <personne datenaissance="1867-11-07" sexe="F"> 
        <nom>CURIE</nom> 
        <prenom>Marie</prenom> 
        <publication>traité de radioactivité </publication> 
    </personne> 
</encyclopedie>
