=== MomoAy/XML/livre2.dtd
<!ELEMENT livre2 (auteur,format)>
<!ATTLIST livre2 id CDATA #REQUIRED
                 nbpages CDATA #REQUIRED
                 titre CDATA #REQUIRED>
<!ELEMENT auteur (nom,prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT format (mesure+)>
<!ATTLIST format type CDATA #REQUIRED>
<!ELEMENT mesure (#PCDATA)>
<!ATTLIST mesure type CDATA #REQUIRED
                 unite CDATA #REQUIRED>

=== MomoAy/XML/livre2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livre2 SYSTEM "livre2.dtd">
<livre2 id="561" nbpages="190" titre="La compagnie des spectres"> 
    <auteur>
        <nom>Salvayre</nom>
        <prenom>Lydie</prenom>
    </auteur>
    <format type="poche">
        <mesure type="largeur" unite="cm">11</mesure> 
        <mesure type="longueur" unite="cm">19</mesure> 
        <mesure type="hauteur" unite="mm">10</mesure>
    </format> 
</livre2>
